on:
  push:
    branches:
      - main  # Use 'main' instead of 'master'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          # Fetch Chrome version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-2)
          echo "Installing ChromeDriver for Chrome version: $CHROME_VERSION"
          
          # Get ChromeDriver version that matches the installed Chrome version
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Downloading ChromeDriver version: $DRIVER_VERSION"
          
          # Download and install ChromeDriver
          wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: |
          cd "Selenium-Version-1/src/test/java"
          mvn test
