name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: |
          cd "Selenium-Version-1"
          mvn clean install

      - name: Run Tests
        run: |
          cd "Selenium-Version-1/src/test/java"
          mvn test
